### ISSUE TITLE
Better styling of list items

### ISSUE THREAD

**Issue by jmartsch** [Brankub/selectik#24]
To style background of active item and the text separately, i added a span in line 98

``` html
html += '<li class="'+ ($this.attr('disabled') === 'disabled' ? 'disabled' : '') +'" data-value="'+$this[0].value+'"><span>'+($this.data('selectik') ? $this.data('selectik') : $this[0].text)+'</span></li>';
```

So with

``` css
.custom-select li span {
padding: 0 10px;
}

.custom-select ul, .custom-select li {
padding: 0;
}
```

you can archive something like this:
![sample2](https://f.cloud.github.com/assets/551551/145417/d7cc1974-7461-11e2-8fb8-6e997ee1b14e.png)
